version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./output_files:/output
    command: parsedmarc --verbose -c /parsedmarc.ini
    depends_on:
      - elasticsearch
    restart: on-failure
#      condition: on-failure
#      delay: 10s
#      max_attempts: 10
#      window: 100s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
